name: fond
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  dio: ^5.8.0+1
  crypto: ^3.0.6
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  typed_data: ^1.4.0
  flutter_gbk2utf8: ^1.0.1
  xml: ^6.5.0
  go_router: ^13.0.1
  provider: ^6.1.1
  flutter_riverpod: ^2.4.10
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  package_info_plus: ^8.3.0
  lunar: ^1.7.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
