name: Flutter Windows Build

on:
  push:
    branches: [master]
  workflow_dispatch: # 允许手动触发工作流

jobs:
  build:
    runs-on: windows-latest # 使用最新的 Windows 运行环境

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3' # 使用指定的 Flutter 版本 3.29.3
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Build Windows application
        run: flutter build windows --release

      - name: Create release ZIP
        run: |
          Compress-Archive -Path build\windows\runner\Release\* -DestinationPath windows_app.zip

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: windows_app.zip
          retention-days: 7
